# Stage 1: Base image with dependencies
FROM python:3.11-slim AS base
WORKDIR /app
COPY requirements/train.txt .
RUN pip install --no-cache-dir -r train.txt


# Stage 2: Training runtime
FROM base AS training

WORKDIR /app

COPY src/ ./src/
COPY configs/ ./configs/

ENV PYTHONUNBUFFERED=1
ENV CONFIG_PATH=/app/configs/training_config.yaml
ENTRYPOINT ["python", "src/train.py"]